# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(811, 526)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tabWidget_laje = QtGui.QTabWidget(self.tab)
        self.tabWidget_laje.setObjectName(_fromUtf8("tabWidget_laje"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label = QtGui.QLabel(self.tab_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.nlaje_cbox_carac_laje = QtGui.QComboBox(self.tab_4)
        self.nlaje_cbox_carac_laje.setObjectName(_fromUtf8("nlaje_cbox_carac_laje"))
        self.nlaje_cbox_carac_laje.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.nlaje_cbox_carac_laje, 0, 1, 1, 1)
        self.add_btn_carac_laje = QtGui.QPushButton(self.tab_4)
        self.add_btn_carac_laje.setObjectName(_fromUtf8("add_btn_carac_laje"))
        self.gridLayout_7.addWidget(self.add_btn_carac_laje, 5, 0, 1, 2)
        self.remov_btn_carac_laje = QtGui.QPushButton(self.tab_4)
        self.remov_btn_carac_laje.setObjectName(_fromUtf8("remov_btn_carac_laje"))
        self.gridLayout_7.addWidget(self.remov_btn_carac_laje, 6, 0, 1, 2)
        self.ly_le_carac_laje = QtGui.QLineEdit(self.tab_4)
        self.ly_le_carac_laje.setObjectName(_fromUtf8("ly_le_carac_laje"))
        self.gridLayout_7.addWidget(self.ly_le_carac_laje, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_7.addWidget(self.label_2, 1, 0, 1, 1)
        self.lx_le_carac_laje = QtGui.QLineEdit(self.tab_4)
        self.lx_le_carac_laje.setObjectName(_fromUtf8("lx_le_carac_laje"))
        self.gridLayout_7.addWidget(self.lx_le_carac_laje, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_7.addWidget(self.label_4, 3, 0, 1, 1)
        self.h_le_carac_laje = QtGui.QLineEdit(self.tab_4)
        self.h_le_carac_laje.setObjectName(_fromUtf8("h_le_carac_laje"))
        self.gridLayout_7.addWidget(self.h_le_carac_laje, 3, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_7.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab_4)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_7.addWidget(self.label_22, 4, 0, 1, 1)
        self.apoio_cbox_carac_laje = QtGui.QComboBox(self.tab_4)
        self.apoio_cbox_carac_laje.setObjectName(_fromUtf8("apoio_cbox_carac_laje"))
        self.apoio_cbox_carac_laje.addItem(_fromUtf8(""))
        self.apoio_cbox_carac_laje.addItem(_fromUtf8(""))
        self.apoio_cbox_carac_laje.addItem(_fromUtf8(""))
        self.apoio_cbox_carac_laje.addItem(_fromUtf8(""))
        self.apoio_cbox_carac_laje.addItem(_fromUtf8(""))
        self.apoio_cbox_carac_laje.addItem(_fromUtf8(""))
        self.apoio_cbox_carac_laje.addItem(_fromUtf8(""))
        self.apoio_cbox_carac_laje.addItem(_fromUtf8(""))
        self.apoio_cbox_carac_laje.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.apoio_cbox_carac_laje, 4, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_7)
        self.textBrowser_carc_laje = QtGui.QTextBrowser(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_carc_laje.setFont(font)
        self.textBrowser_carc_laje.setObjectName(_fromUtf8("textBrowser_carc_laje"))
        self.horizontalLayout_5.addWidget(self.textBrowser_carc_laje)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.tabWidget_laje.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_16 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setVerticalSpacing(20)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.perimetro_parede_le_carg_laje = QtGui.QLineEdit(self.groupBox_4)
        self.perimetro_parede_le_carg_laje.setObjectName(_fromUtf8("perimetro_parede_le_carg_laje"))
        self.gridLayout_15.addWidget(self.perimetro_parede_le_carg_laje, 2, 1, 1, 1)
        self.caso_parede_cbox_carg_laje = QtGui.QComboBox(self.groupBox_4)
        self.caso_parede_cbox_carg_laje.setObjectName(_fromUtf8("caso_parede_cbox_carg_laje"))
        self.caso_parede_cbox_carg_laje.addItem(_fromUtf8(""))
        self.caso_parede_cbox_carg_laje.addItem(_fromUtf8(""))
        self.caso_parede_cbox_carg_laje.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.caso_parede_cbox_carg_laje, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_15.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_15.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_15.addWidget(self.label_16, 2, 0, 1, 1)
        self.espessura_parede_le_carg_laje = QtGui.QLineEdit(self.groupBox_4)
        self.espessura_parede_le_carg_laje.setObjectName(_fromUtf8("espessura_parede_le_carg_laje"))
        self.gridLayout_15.addWidget(self.espessura_parede_le_carg_laje, 1, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox_4)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_15.addWidget(self.label_30, 3, 0, 1, 1)
        self.altura_parede_le_carg_laje = QtGui.QLineEdit(self.groupBox_4)
        self.altura_parede_le_carg_laje.setObjectName(_fromUtf8("altura_parede_le_carg_laje"))
        self.gridLayout_15.addWidget(self.altura_parede_le_carg_laje, 3, 1, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_4, 3, 0, 1, 2)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_18 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_17.addWidget(self.label_17, 0, 0, 1, 1)
        self.utiliz_le_carg_laje = QtGui.QLineEdit(self.groupBox_5)
        self.utiliz_le_carg_laje.setObjectName(_fromUtf8("utiliz_le_carg_laje"))
        self.gridLayout_17.addWidget(self.utiliz_le_carg_laje, 0, 1, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_5, 3, 2, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setVerticalSpacing(20)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_11.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_11.addWidget(self.label_11, 0, 0, 1, 1)
        self.peso_revest_inf_le_carg_laje = QtGui.QLineEdit(self.groupBox_2)
        self.peso_revest_inf_le_carg_laje.setObjectName(_fromUtf8("peso_revest_inf_le_carg_laje"))
        self.gridLayout_11.addWidget(self.peso_revest_inf_le_carg_laje, 1, 1, 1, 1)
        self.espessura_revest_inf_le_carg_laje = QtGui.QLineEdit(self.groupBox_2)
        self.espessura_revest_inf_le_carg_laje.setObjectName(_fromUtf8("espessura_revest_inf_le_carg_laje"))
        self.gridLayout_11.addWidget(self.espessura_revest_inf_le_carg_laje, 0, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 1, 2, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setVerticalSpacing(20)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_13.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_13.addWidget(self.label_14, 1, 0, 1, 1)
        self.espessura_contrap_le_carg_laje = QtGui.QLineEdit(self.groupBox_3)
        self.espessura_contrap_le_carg_laje.setObjectName(_fromUtf8("espessura_contrap_le_carg_laje"))
        self.gridLayout_13.addWidget(self.espessura_contrap_le_carg_laje, 0, 1, 1, 1)
        self.peso_contrap_le_carg_laje = QtGui.QLineEdit(self.groupBox_3)
        self.peso_contrap_le_carg_laje.setObjectName(_fromUtf8("peso_contrap_le_carg_laje"))
        self.gridLayout_13.addWidget(self.peso_contrap_le_carg_laje, 1, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 1, 3, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_9.setVerticalSpacing(20)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_9.addWidget(self.label_8, 0, 0, 1, 1)
        self.espessura_revest_sup_le_carg_laje = QtGui.QLineEdit(self.groupBox)
        self.espessura_revest_sup_le_carg_laje.setObjectName(_fromUtf8("espessura_revest_sup_le_carg_laje"))
        self.gridLayout_9.addWidget(self.espessura_revest_sup_le_carg_laje, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_9.addWidget(self.label_9, 1, 0, 1, 1)
        self.peso_revest_sup_le_carg_laje = QtGui.QLineEdit(self.groupBox)
        self.peso_revest_sup_le_carg_laje.setObjectName(_fromUtf8("peso_revest_sup_le_carg_laje"))
        self.gridLayout_9.addWidget(self.peso_revest_sup_le_carg_laje, 1, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 1, 0, 1, 2)
        self.textBrowser_carg_laje = QtGui.QTextBrowser(self.tab_5)
        self.textBrowser_carg_laje.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_carg_laje.setFont(font)
        self.textBrowser_carg_laje.setObjectName(_fromUtf8("textBrowser_carg_laje"))
        self.gridLayout_5.addWidget(self.textBrowser_carg_laje, 0, 4, 4, 1)
        self.label_5 = QtGui.QLabel(self.tab_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.add_btn_carg_laje = QtGui.QPushButton(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_btn_carg_laje.sizePolicy().hasHeightForWidth())
        self.add_btn_carg_laje.setSizePolicy(sizePolicy)
        self.add_btn_carg_laje.setObjectName(_fromUtf8("add_btn_carg_laje"))
        self.gridLayout_5.addWidget(self.add_btn_carg_laje, 3, 3, 1, 1)
        self.nlaje_cbox_carg_laje = QtGui.QComboBox(self.tab_5)
        self.nlaje_cbox_carg_laje.setObjectName(_fromUtf8("nlaje_cbox_carg_laje"))
        self.gridLayout_5.addWidget(self.nlaje_cbox_carg_laje, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 2, 1, 1)
        self.tabWidget_laje.addTab(self.tab_5, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_11)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_21 = QtGui.QGridLayout()
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.label_32 = QtGui.QLabel(self.tab_11)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_21.addWidget(self.label_32, 4, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.tab_11)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_21.addWidget(self.label_31, 5, 0, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab_11)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_21.addWidget(self.label_33, 3, 0, 1, 1)
        self.nlaje_cbox_reac_laje = QtGui.QComboBox(self.tab_11)
        self.nlaje_cbox_reac_laje.setObjectName(_fromUtf8("nlaje_cbox_reac_laje"))
        self.gridLayout_21.addWidget(self.nlaje_cbox_reac_laje, 0, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.tab_11)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_21.addWidget(self.label_35, 1, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.tab_11)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_21.addWidget(self.label_36, 2, 0, 1, 1)
        self.label_34 = QtGui.QLabel(self.tab_11)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_21.addWidget(self.label_34, 0, 0, 1, 1)
        self.vx_le_reac_laje = QtGui.QLineEdit(self.tab_11)
        self.vx_le_reac_laje.setObjectName(_fromUtf8("vx_le_reac_laje"))
        self.gridLayout_21.addWidget(self.vx_le_reac_laje, 2, 1, 1, 1)
        self.lambda_le_reac_laje = QtGui.QLineEdit(self.tab_11)
        self.lambda_le_reac_laje.setEnabled(True)
        self.lambda_le_reac_laje.setText(_fromUtf8(""))
        self.lambda_le_reac_laje.setReadOnly(True)
        self.lambda_le_reac_laje.setObjectName(_fromUtf8("lambda_le_reac_laje"))
        self.gridLayout_21.addWidget(self.lambda_le_reac_laje, 1, 1, 1, 1)
        self.v_x_le_reac_laje = QtGui.QLineEdit(self.tab_11)
        self.v_x_le_reac_laje.setObjectName(_fromUtf8("v_x_le_reac_laje"))
        self.gridLayout_21.addWidget(self.v_x_le_reac_laje, 3, 1, 1, 1)
        self.v_y_le_reac_laje = QtGui.QLineEdit(self.tab_11)
        self.v_y_le_reac_laje.setObjectName(_fromUtf8("v_y_le_reac_laje"))
        self.gridLayout_21.addWidget(self.v_y_le_reac_laje, 5, 1, 1, 1)
        self.vy_le_reac_laje = QtGui.QLineEdit(self.tab_11)
        self.vy_le_reac_laje.setObjectName(_fromUtf8("vy_le_reac_laje"))
        self.gridLayout_21.addWidget(self.vy_le_reac_laje, 4, 1, 1, 1)
        self.add_btn_reac_laje = QtGui.QPushButton(self.tab_11)
        self.add_btn_reac_laje.setObjectName(_fromUtf8("add_btn_reac_laje"))
        self.gridLayout_21.addWidget(self.add_btn_reac_laje, 6, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout_21, 0, 0, 1, 1)
        self.textBrowser_reac_laje = QtGui.QTextBrowser(self.tab_11)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_reac_laje.setFont(font)
        self.textBrowser_reac_laje.setObjectName(_fromUtf8("textBrowser_reac_laje"))
        self.gridLayout_3.addWidget(self.textBrowser_reac_laje, 0, 1, 1, 1)
        self.tabWidget_laje.addTab(self.tab_11, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_20 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.textBrowser_momentos_laje = QtGui.QTextBrowser(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_momentos_laje.setFont(font)
        self.textBrowser_momentos_laje.setObjectName(_fromUtf8("textBrowser_momentos_laje"))
        self.gridLayout_20.addWidget(self.textBrowser_momentos_laje, 0, 1, 1, 1)
        self.gridLayout_19 = QtGui.QGridLayout()
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.label_23 = QtGui.QLabel(self.tab_6)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_19.addWidget(self.label_23, 3, 0, 1, 1)
        self.nlaje_cbox_momento_laje = QtGui.QComboBox(self.tab_6)
        self.nlaje_cbox_momento_laje.setObjectName(_fromUtf8("nlaje_cbox_momento_laje"))
        self.gridLayout_19.addWidget(self.nlaje_cbox_momento_laje, 0, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_6)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_19.addWidget(self.label_24, 4, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_6)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_19.addWidget(self.label_25, 5, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab_6)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_19.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab_6)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_19.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_6)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_19.addWidget(self.label_21, 2, 0, 1, 1)
        self.lambda_le_momento_laje = QtGui.QLineEdit(self.tab_6)
        self.lambda_le_momento_laje.setEnabled(True)
        self.lambda_le_momento_laje.setReadOnly(True)
        self.lambda_le_momento_laje.setObjectName(_fromUtf8("lambda_le_momento_laje"))
        self.gridLayout_19.addWidget(self.lambda_le_momento_laje, 1, 1, 1, 1)
        self.mx_le_momento_laje = QtGui.QLineEdit(self.tab_6)
        self.mx_le_momento_laje.setObjectName(_fromUtf8("mx_le_momento_laje"))
        self.gridLayout_19.addWidget(self.mx_le_momento_laje, 2, 1, 1, 1)
        self.nx_le_momento_laje = QtGui.QLineEdit(self.tab_6)
        self.nx_le_momento_laje.setObjectName(_fromUtf8("nx_le_momento_laje"))
        self.gridLayout_19.addWidget(self.nx_le_momento_laje, 3, 1, 1, 1)
        self.my_le_momento_laje = QtGui.QLineEdit(self.tab_6)
        self.my_le_momento_laje.setObjectName(_fromUtf8("my_le_momento_laje"))
        self.gridLayout_19.addWidget(self.my_le_momento_laje, 4, 1, 1, 1)
        self.add_btn_momento_laje = QtGui.QPushButton(self.tab_6)
        self.add_btn_momento_laje.setObjectName(_fromUtf8("add_btn_momento_laje"))
        self.gridLayout_19.addWidget(self.add_btn_momento_laje, 6, 0, 1, 2)
        self.ny_le_momento_laje = QtGui.QLineEdit(self.tab_6)
        self.ny_le_momento_laje.setObjectName(_fromUtf8("ny_le_momento_laje"))
        self.gridLayout_19.addWidget(self.ny_le_momento_laje, 5, 1, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        self.tabWidget_laje.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tab_7)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.gridLayout_22 = QtGui.QGridLayout()
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.compat_table_compat_laje = QtGui.QTableWidget(self.tab_7)
        self.compat_table_compat_laje.setShowGrid(True)
        self.compat_table_compat_laje.setObjectName(_fromUtf8("compat_table_compat_laje"))
        self.compat_table_compat_laje.setColumnCount(4)
        self.compat_table_compat_laje.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.compat_table_compat_laje.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.compat_table_compat_laje.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.compat_table_compat_laje.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.compat_table_compat_laje.setHorizontalHeaderItem(3, item)
        self.gridLayout_22.addWidget(self.compat_table_compat_laje, 1, 0, 1, 2)
        self.add_compt_btn_compat_laje = QtGui.QPushButton(self.tab_7)
        self.add_compt_btn_compat_laje.setObjectName(_fromUtf8("add_compt_btn_compat_laje"))
        self.gridLayout_22.addWidget(self.add_compt_btn_compat_laje, 4, 0, 1, 2)
        self.add_linha_btn_compat_laje = QtGui.QPushButton(self.tab_7)
        self.add_linha_btn_compat_laje.setObjectName(_fromUtf8("add_linha_btn_compat_laje"))
        self.gridLayout_22.addWidget(self.add_linha_btn_compat_laje, 3, 0, 1, 1)
        self.remov_linha_btn_compat_laje = QtGui.QPushButton(self.tab_7)
        self.remov_linha_btn_compat_laje.setObjectName(_fromUtf8("remov_linha_btn_compat_laje"))
        self.gridLayout_22.addWidget(self.remov_linha_btn_compat_laje, 3, 1, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_22)
        self.textBrowser_compat_laje = QtGui.QTextBrowser(self.tab_7)
        self.textBrowser_compat_laje.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_compat_laje.setFont(font)
        self.textBrowser_compat_laje.setObjectName(_fromUtf8("textBrowser_compat_laje"))
        self.horizontalLayout_7.addWidget(self.textBrowser_compat_laje)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.tabWidget_laje.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.tab_8)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.gridLayout_24 = QtGui.QGridLayout()
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.nlaje_cbox_dim_laje = QtGui.QComboBox(self.tab_8)
        self.nlaje_cbox_dim_laje.setObjectName(_fromUtf8("nlaje_cbox_dim_laje"))
        self.gridLayout_24.addWidget(self.nlaje_cbox_dim_laje, 0, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.tab_8)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_24.addWidget(self.label_28, 2, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.tab_8)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_24.addWidget(self.label_27, 1, 0, 1, 1)
        self.diametro_le_dim_laje = QtGui.QLineEdit(self.tab_8)
        self.diametro_le_dim_laje.setObjectName(_fromUtf8("diametro_le_dim_laje"))
        self.gridLayout_24.addWidget(self.diametro_le_dim_laje, 2, 1, 1, 1)
        self.espac_le_dim_laje = QtGui.QLineEdit(self.tab_8)
        self.espac_le_dim_laje.setObjectName(_fromUtf8("espac_le_dim_laje"))
        self.gridLayout_24.addWidget(self.espac_le_dim_laje, 3, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.tab_8)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_24.addWidget(self.label_29, 3, 0, 1, 1)
        self.sec_cbox_dim_laje = QtGui.QComboBox(self.tab_8)
        self.sec_cbox_dim_laje.setObjectName(_fromUtf8("sec_cbox_dim_laje"))
        self.gridLayout_24.addWidget(self.sec_cbox_dim_laje, 1, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.tab_8)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_24.addWidget(self.label_26, 0, 0, 1, 1)
        self.add_btn_dim_laje = QtGui.QPushButton(self.tab_8)
        self.add_btn_dim_laje.setObjectName(_fromUtf8("add_btn_dim_laje"))
        self.gridLayout_24.addWidget(self.add_btn_dim_laje, 4, 0, 1, 2)
        self.horizontalLayout_9.addLayout(self.gridLayout_24)
        self.textBrowser_dim_laje = QtGui.QTextBrowser(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_dim_laje.setFont(font)
        self.textBrowser_dim_laje.setObjectName(_fromUtf8("textBrowser_dim_laje"))
        self.horizontalLayout_9.addWidget(self.textBrowser_dim_laje)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.tabWidget_laje.addTab(self.tab_8, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget_laje, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArquivo = QtGui.QMenu(self.menubar)
        self.menuArquivo.setObjectName(_fromUtf8("menuArquivo"))
        self.menuAjuda = QtGui.QMenu(self.menubar)
        self.menuAjuda.setObjectName(_fromUtf8("menuAjuda"))
        self.menuConfigura_es = QtGui.QMenu(self.menubar)
        self.menuConfigura_es.setObjectName(_fromUtf8("menuConfigura_es"))
        self.menuCalcular = QtGui.QMenu(self.menubar)
        self.menuCalcular.setObjectName(_fromUtf8("menuCalcular"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNovo = QtGui.QAction(MainWindow)
        self.actionNovo.setObjectName(_fromUtf8("actionNovo"))
        self.actionAbrir = QtGui.QAction(MainWindow)
        self.actionAbrir.setObjectName(_fromUtf8("actionAbrir"))
        self.actionSalvar = QtGui.QAction(MainWindow)
        self.actionSalvar.setObjectName(_fromUtf8("actionSalvar"))
        self.actionSalvar_Como = QtGui.QAction(MainWindow)
        self.actionSalvar_Como.setObjectName(_fromUtf8("actionSalvar_Como"))
        self.actionSair = QtGui.QAction(MainWindow)
        self.actionSair.setObjectName(_fromUtf8("actionSair"))
        self.actionSobre = QtGui.QAction(MainWindow)
        self.actionSobre.setObjectName(_fromUtf8("actionSobre"))
        self.actionDevelopment_Tool = QtGui.QAction(MainWindow)
        self.actionDevelopment_Tool.setObjectName(_fromUtf8("actionDevelopment_Tool"))
        self.actionCoeficientes_de_Norma = QtGui.QAction(MainWindow)
        self.actionCoeficientes_de_Norma.setObjectName(_fromUtf8("actionCoeficientes_de_Norma"))
        self.actionPesos_Espec_ficos = QtGui.QAction(MainWindow)
        self.actionPesos_Espec_ficos.setObjectName(_fromUtf8("actionPesos_Espec_ficos"))
        self.actionDimensionar_Lajes = QtGui.QAction(MainWindow)
        self.actionDimensionar_Lajes.setObjectName(_fromUtf8("actionDimensionar_Lajes"))
        self.actionDimensionar_Vigas = QtGui.QAction(MainWindow)
        self.actionDimensionar_Vigas.setObjectName(_fromUtf8("actionDimensionar_Vigas"))
        self.actionDimensionar_Pilares = QtGui.QAction(MainWindow)
        self.actionDimensionar_Pilares.setObjectName(_fromUtf8("actionDimensionar_Pilares"))
        self.menuArquivo.addAction(self.actionNovo)
        self.menuArquivo.addAction(self.actionAbrir)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionSalvar)
        self.menuArquivo.addAction(self.actionSalvar_Como)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionSair)
        self.menuAjuda.addAction(self.actionSobre)
        self.menuAjuda.addSeparator()
        self.menuAjuda.addAction(self.actionDevelopment_Tool)
        self.menuConfigura_es.addAction(self.actionCoeficientes_de_Norma)
        self.menuConfigura_es.addAction(self.actionPesos_Espec_ficos)
        self.menuCalcular.addAction(self.actionDimensionar_Lajes)
        self.menuCalcular.addAction(self.actionDimensionar_Vigas)
        self.menuCalcular.addAction(self.actionDimensionar_Pilares)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuConfigura_es.menuAction())
        self.menubar.addAction(self.menuCalcular.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_laje.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.tabWidget_laje)
        MainWindow.setTabOrder(self.tabWidget_laje, self.nlaje_cbox_carac_laje)
        MainWindow.setTabOrder(self.nlaje_cbox_carac_laje, self.lx_le_carac_laje)
        MainWindow.setTabOrder(self.lx_le_carac_laje, self.ly_le_carac_laje)
        MainWindow.setTabOrder(self.ly_le_carac_laje, self.h_le_carac_laje)
        MainWindow.setTabOrder(self.h_le_carac_laje, self.apoio_cbox_carac_laje)
        MainWindow.setTabOrder(self.apoio_cbox_carac_laje, self.add_btn_carac_laje)
        MainWindow.setTabOrder(self.add_btn_carac_laje, self.remov_btn_carac_laje)
        MainWindow.setTabOrder(self.remov_btn_carac_laje, self.textBrowser_carc_laje)
        MainWindow.setTabOrder(self.textBrowser_carc_laje, self.nlaje_cbox_carg_laje)
        MainWindow.setTabOrder(self.nlaje_cbox_carg_laje, self.espessura_revest_sup_le_carg_laje)
        MainWindow.setTabOrder(self.espessura_revest_sup_le_carg_laje, self.peso_revest_sup_le_carg_laje)
        MainWindow.setTabOrder(self.peso_revest_sup_le_carg_laje, self.espessura_revest_inf_le_carg_laje)
        MainWindow.setTabOrder(self.espessura_revest_inf_le_carg_laje, self.peso_revest_inf_le_carg_laje)
        MainWindow.setTabOrder(self.peso_revest_inf_le_carg_laje, self.espessura_contrap_le_carg_laje)
        MainWindow.setTabOrder(self.espessura_contrap_le_carg_laje, self.peso_contrap_le_carg_laje)
        MainWindow.setTabOrder(self.peso_contrap_le_carg_laje, self.caso_parede_cbox_carg_laje)
        MainWindow.setTabOrder(self.caso_parede_cbox_carg_laje, self.espessura_parede_le_carg_laje)
        MainWindow.setTabOrder(self.espessura_parede_le_carg_laje, self.perimetro_parede_le_carg_laje)
        MainWindow.setTabOrder(self.perimetro_parede_le_carg_laje, self.altura_parede_le_carg_laje)
        MainWindow.setTabOrder(self.altura_parede_le_carg_laje, self.utiliz_le_carg_laje)
        MainWindow.setTabOrder(self.utiliz_le_carg_laje, self.add_btn_carg_laje)
        MainWindow.setTabOrder(self.add_btn_carg_laje, self.textBrowser_carg_laje)
        MainWindow.setTabOrder(self.textBrowser_carg_laje, self.nlaje_cbox_reac_laje)
        MainWindow.setTabOrder(self.nlaje_cbox_reac_laje, self.lambda_le_reac_laje)
        MainWindow.setTabOrder(self.lambda_le_reac_laje, self.vx_le_reac_laje)
        MainWindow.setTabOrder(self.vx_le_reac_laje, self.v_x_le_reac_laje)
        MainWindow.setTabOrder(self.v_x_le_reac_laje, self.vy_le_reac_laje)
        MainWindow.setTabOrder(self.vy_le_reac_laje, self.v_y_le_reac_laje)
        MainWindow.setTabOrder(self.v_y_le_reac_laje, self.add_btn_reac_laje)
        MainWindow.setTabOrder(self.add_btn_reac_laje, self.textBrowser_reac_laje)
        MainWindow.setTabOrder(self.textBrowser_reac_laje, self.nlaje_cbox_momento_laje)
        MainWindow.setTabOrder(self.nlaje_cbox_momento_laje, self.lambda_le_momento_laje)
        MainWindow.setTabOrder(self.lambda_le_momento_laje, self.mx_le_momento_laje)
        MainWindow.setTabOrder(self.mx_le_momento_laje, self.nx_le_momento_laje)
        MainWindow.setTabOrder(self.nx_le_momento_laje, self.my_le_momento_laje)
        MainWindow.setTabOrder(self.my_le_momento_laje, self.ny_le_momento_laje)
        MainWindow.setTabOrder(self.ny_le_momento_laje, self.add_btn_momento_laje)
        MainWindow.setTabOrder(self.add_btn_momento_laje, self.textBrowser_momentos_laje)
        MainWindow.setTabOrder(self.textBrowser_momentos_laje, self.compat_table_compat_laje)
        MainWindow.setTabOrder(self.compat_table_compat_laje, self.add_linha_btn_compat_laje)
        MainWindow.setTabOrder(self.add_linha_btn_compat_laje, self.remov_linha_btn_compat_laje)
        MainWindow.setTabOrder(self.remov_linha_btn_compat_laje, self.add_compt_btn_compat_laje)
        MainWindow.setTabOrder(self.add_compt_btn_compat_laje, self.textBrowser_compat_laje)
        MainWindow.setTabOrder(self.textBrowser_compat_laje, self.nlaje_cbox_dim_laje)
        MainWindow.setTabOrder(self.nlaje_cbox_dim_laje, self.sec_cbox_dim_laje)
        MainWindow.setTabOrder(self.sec_cbox_dim_laje, self.diametro_le_dim_laje)
        MainWindow.setTabOrder(self.diametro_le_dim_laje, self.espac_le_dim_laje)
        MainWindow.setTabOrder(self.espac_le_dim_laje, self.add_btn_dim_laje)
        MainWindow.setTabOrder(self.add_btn_dim_laje, self.textBrowser_dim_laje)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ConcretePy", None))
        self.label.setText(_translate("MainWindow", "Número da laje", None))
        self.nlaje_cbox_carac_laje.setItemText(0, _translate("MainWindow", "1", None))
        self.add_btn_carac_laje.setText(_translate("MainWindow", "Adicionar Laje", None))
        self.remov_btn_carac_laje.setText(_translate("MainWindow", "Remover Laje", None))
        self.ly_le_carac_laje.setPlaceholderText(_translate("MainWindow", "ly", None))
        self.label_2.setText(_translate("MainWindow", "Comprimento da direção principal (cm)", None))
        self.lx_le_carac_laje.setPlaceholderText(_translate("MainWindow", "lx", None))
        self.label_4.setText(_translate("MainWindow", "Espessura de pré-dimensionamento (cm)", None))
        self.h_le_carac_laje.setPlaceholderText(_translate("MainWindow", "h", None))
        self.label_3.setText(_translate("MainWindow", "Comprimento da direção secundária (cm)", None))
        self.label_22.setText(_translate("MainWindow", "Tipo de Apoio", None))
        self.apoio_cbox_carac_laje.setItemText(0, _translate("MainWindow", "Caso 1 - Ax1-Ax2-Ay1-Ay2", None))
        self.apoio_cbox_carac_laje.setItemText(1, _translate("MainWindow", "Caso 2A - Ex1-Ax2-Ay1-Ay2", None))
        self.apoio_cbox_carac_laje.setItemText(2, _translate("MainWindow", "Caso 2B - Ax1-Ax2-Ey1-Ay2", None))
        self.apoio_cbox_carac_laje.setItemText(3, _translate("MainWindow", "Caso 3 - Ex1-Ax2-Ey1-Ay2", None))
        self.apoio_cbox_carac_laje.setItemText(4, _translate("MainWindow", "Caso 4A - Ex1-Ex2-Ay1-Ay2", None))
        self.apoio_cbox_carac_laje.setItemText(5, _translate("MainWindow", "Caso 4B - Ax1-Ax2-Ey1-Ey2", None))
        self.apoio_cbox_carac_laje.setItemText(6, _translate("MainWindow", "Caso 5A - Ex1-Ex2-Ey1-Ay2", None))
        self.apoio_cbox_carac_laje.setItemText(7, _translate("MainWindow", "Caso 5B - Ex1-Ax2-Ey1-Ey2", None))
        self.apoio_cbox_carac_laje.setItemText(8, _translate("MainWindow", "Caso 6 - Ex1-Ex2-Ey1-Ey2", None))
        self.textBrowser_carc_laje.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.tabWidget_laje.setTabText(self.tabWidget_laje.indexOf(self.tab_4), _translate("MainWindow", "Caracterização", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Parede", None))
        self.caso_parede_cbox_carg_laje.setItemText(0, _translate("MainWindow", "Laje em cruz", None))
        self.caso_parede_cbox_carg_laje.setItemText(1, _translate("MainWindow", "Paralelo ao menor vão", None))
        self.caso_parede_cbox_carg_laje.setItemText(2, _translate("MainWindow", "Perpendicular ao menor vão", None))
        self.label_6.setText(_translate("MainWindow", "Caso", None))
        self.label_15.setText(_translate("MainWindow", "Espessura (cm)", None))
        self.label_16.setText(_translate("MainWindow", "Perímetro (cm)", None))
        self.label_30.setText(_translate("MainWindow", "Altura (cm)", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Acidental, Utilização e Serviço", None))
        self.label_17.setText(_translate("MainWindow", "Carga (kN/m²)", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Revestimento Inferior", None))
        self.label_12.setText(_translate("MainWindow", "Peso Específico (kN/m³)", None))
        self.label_11.setText(_translate("MainWindow", "Espessura (cm)", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Contrapiso", None))
        self.label_13.setText(_translate("MainWindow", "Espessura (cm)", None))
        self.label_14.setText(_translate("MainWindow", "Peso Específico (kN/m³)", None))
        self.groupBox.setTitle(_translate("MainWindow", "Revestimento Superior", None))
        self.label_8.setText(_translate("MainWindow", "Espessura (cm)", None))
        self.label_9.setText(_translate("MainWindow", "Peso Específico (kN/m³)", None))
        self.label_5.setText(_translate("MainWindow", "Número da Laje", None))
        self.add_btn_carg_laje.setText(_translate("MainWindow", "Adicionar Para Essa Laje", None))
        self.tabWidget_laje.setTabText(self.tabWidget_laje.indexOf(self.tab_5), _translate("MainWindow", "Cargas", None))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">ν</span><span style=\" font-size:12pt; vertical-align:sub;\">y</span></p></body></html>", None))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">ν\'</span><span style=\" font-size:12pt; vertical-align:sub;\">y</span></p></body></html>", None))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">ν\'</span><span style=\" font-size:11pt; vertical-align:sub;\">x</span></p></body></html>", None))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">λ</span></p></body></html>", None))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">ν</span><span style=\" font-size:11pt; vertical-align:sub;\">x</span></p></body></html>", None))
        self.label_34.setText(_translate("MainWindow", "Número da Laje", None))
        self.add_btn_reac_laje.setText(_translate("MainWindow", "Confirmar Reações", None))
        self.tabWidget_laje.setTabText(self.tabWidget_laje.indexOf(self.tab_11), _translate("MainWindow", "Reações", None))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">μ\'</span><span style=\" font-size:12pt; vertical-align:sub;\">x</span></p></body></html>", None))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">μ</span><span style=\" font-size:12pt; vertical-align:sub;\">y</span></p></body></html>", None))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">μ\'</span><span style=\" font-size:12pt; vertical-align:sub;\">y</span></p></body></html>", None))
        self.label_18.setText(_translate("MainWindow", "Número da Laje", None))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">λ</span></p></body></html>", None))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">μ</span><span style=\" font-size:12pt; vertical-align:sub;\">x</span></p></body></html>", None))
        self.add_btn_momento_laje.setText(_translate("MainWindow", "Confirmar Momentos", None))
        self.tabWidget_laje.setTabText(self.tabWidget_laje.indexOf(self.tab_6), _translate("MainWindow", "Momentos", None))
        self.compat_table_compat_laje.setSortingEnabled(False)
        item = self.compat_table_compat_laje.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Laje A", None))
        item = self.compat_table_compat_laje.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Bordo A", None))
        item = self.compat_table_compat_laje.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Laje B", None))
        item = self.compat_table_compat_laje.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Bordo B", None))
        self.add_compt_btn_compat_laje.setText(_translate("MainWindow", "Compatibilizar Momentos", None))
        self.add_linha_btn_compat_laje.setText(_translate("MainWindow", "Adicionar Linha", None))
        self.remov_linha_btn_compat_laje.setText(_translate("MainWindow", "Remover Linha", None))
        self.tabWidget_laje.setTabText(self.tabWidget_laje.indexOf(self.tab_7), _translate("MainWindow", "Compatibilização", None))
        self.label_28.setText(_translate("MainWindow", "Diâmetro (mm)", None))
        self.label_27.setText(_translate("MainWindow", "Seção", None))
        self.label_29.setText(_translate("MainWindow", "Espaçamento (cm)", None))
        self.label_26.setText(_translate("MainWindow", "Número da Laje", None))
        self.add_btn_dim_laje.setText(_translate("MainWindow", "Redimensionar", None))
        self.tabWidget_laje.setTabText(self.tabWidget_laje.indexOf(self.tab_8), _translate("MainWindow", "Dimensionamento", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Lajes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Vigas", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Pilares", None))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo", None))
        self.menuAjuda.setTitle(_translate("MainWindow", "Ajuda", None))
        self.menuConfigura_es.setTitle(_translate("MainWindow", "Configurações", None))
        self.menuCalcular.setTitle(_translate("MainWindow", "Calcular", None))
        self.actionNovo.setText(_translate("MainWindow", "Novo...", None))
        self.actionNovo.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir...", None))
        self.actionAbrir.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionSalvar.setText(_translate("MainWindow", "Salvar", None))
        self.actionSalvar.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionSalvar_Como.setText(_translate("MainWindow", "Salvar Como...", None))
        self.actionSalvar_Como.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.actionSair.setText(_translate("MainWindow", "Sair", None))
        self.actionSair.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionSobre.setText(_translate("MainWindow", "Sobre", None))
        self.actionSobre.setShortcut(_translate("MainWindow", "F1", None))
        self.actionDevelopment_Tool.setText(_translate("MainWindow", "Development Tool", None))
        self.actionDevelopment_Tool.setShortcut(_translate("MainWindow", "F10", None))
        self.actionCoeficientes_de_Norma.setText(_translate("MainWindow", "Coeficientes de Norma...", None))
        self.actionPesos_Espec_ficos.setText(_translate("MainWindow", "Pesos Específicos...", None))
        self.actionDimensionar_Lajes.setText(_translate("MainWindow", "Dimensionar Lajes", None))
        self.actionDimensionar_Lajes.setShortcut(_translate("MainWindow", "Ctrl+!", None))
        self.actionDimensionar_Vigas.setText(_translate("MainWindow", "Dimensionar Vigas", None))
        self.actionDimensionar_Vigas.setShortcut(_translate("MainWindow", "Ctrl+@", None))
        self.actionDimensionar_Pilares.setText(_translate("MainWindow", "Dimensionar Pilares", None))
        self.actionDimensionar_Pilares.setShortcut(_translate("MainWindow", "Ctrl+#", None))

