# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowGUI.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(825, 471)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget_laje = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_laje.setObjectName("tabWidget_laje")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.splitter = QtWidgets.QSplitter(self.tab_4)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.widget)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 4, 0, 1, 1)
        self.nlaje_cbox_carac_laje = QtWidgets.QComboBox(self.widget)
        self.nlaje_cbox_carac_laje.setObjectName("nlaje_cbox_carac_laje")
        self.nlaje_cbox_carac_laje.addItem("")
        self.gridLayout_7.addWidget(self.nlaje_cbox_carac_laje, 0, 1, 1, 1)
        self.remov_btn_carac_laje = QtWidgets.QPushButton(self.widget)
        self.remov_btn_carac_laje.setObjectName("remov_btn_carac_laje")
        self.gridLayout_7.addWidget(self.remov_btn_carac_laje, 6, 0, 1, 2)
        self.apoio_cbox_carac_laje = QtWidgets.QComboBox(self.widget)
        self.apoio_cbox_carac_laje.setObjectName("apoio_cbox_carac_laje")
        self.apoio_cbox_carac_laje.addItem("")
        self.apoio_cbox_carac_laje.addItem("")
        self.apoio_cbox_carac_laje.addItem("")
        self.apoio_cbox_carac_laje.addItem("")
        self.apoio_cbox_carac_laje.addItem("")
        self.apoio_cbox_carac_laje.addItem("")
        self.apoio_cbox_carac_laje.addItem("")
        self.apoio_cbox_carac_laje.addItem("")
        self.apoio_cbox_carac_laje.addItem("")
        self.gridLayout_7.addWidget(self.apoio_cbox_carac_laje, 4, 1, 1, 1)
        self.lx_le_carac_laje = QtWidgets.QLineEdit(self.widget)
        self.lx_le_carac_laje.setObjectName("lx_le_carac_laje")
        self.gridLayout_7.addWidget(self.lx_le_carac_laje, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 3, 0, 1, 1)
        self.h_le_carac_laje = QtWidgets.QLineEdit(self.widget)
        self.h_le_carac_laje.setObjectName("h_le_carac_laje")
        self.gridLayout_7.addWidget(self.h_le_carac_laje, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 2, 0, 1, 1)
        self.add_btn_carac_laje = QtWidgets.QPushButton(self.widget)
        self.add_btn_carac_laje.setObjectName("add_btn_carac_laje")
        self.gridLayout_7.addWidget(self.add_btn_carac_laje, 5, 0, 1, 2)
        self.ly_le_carac_laje = QtWidgets.QLineEdit(self.widget)
        self.ly_le_carac_laje.setObjectName("ly_le_carac_laje")
        self.gridLayout_7.addWidget(self.ly_le_carac_laje, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.textBrowser_carc_laje = QtWidgets.QTextBrowser(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_carc_laje.setFont(font)
        self.textBrowser_carc_laje.setObjectName("textBrowser_carc_laje")
        self.gridLayout_23.addWidget(self.splitter, 0, 0, 1, 1)
        self.tabWidget_laje.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter_2 = QtWidgets.QSplitter(self.tab_5)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.widget_2 = QtWidgets.QWidget(self.splitter_2)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.nlaje_cbox_carg_laje = QtWidgets.QComboBox(self.widget_2)
        self.nlaje_cbox_carg_laje.setObjectName("nlaje_cbox_carg_laje")
        self.gridLayout_4.addWidget(self.nlaje_cbox_carg_laje, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 0, 0, 1, 1)
        self.espessura_revest_sup_le_carg_laje = QtWidgets.QLineEdit(self.groupBox)
        self.espessura_revest_sup_le_carg_laje.setObjectName("espessura_revest_sup_le_carg_laje")
        self.gridLayout_9.addWidget(self.espessura_revest_sup_le_carg_laje, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 1, 0, 1, 1)
        self.peso_revest_sup_le_carg_laje = QtWidgets.QLineEdit(self.groupBox)
        self.peso_revest_sup_le_carg_laje.setObjectName("peso_revest_sup_le_carg_laje")
        self.gridLayout_9.addWidget(self.peso_revest_sup_le_carg_laje, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 1, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_10.addWidget(self.label_11, 0, 0, 1, 1)
        self.espessura_revest_inf_le_carg_laje = QtWidgets.QLineEdit(self.groupBox_2)
        self.espessura_revest_inf_le_carg_laje.setObjectName("espessura_revest_inf_le_carg_laje")
        self.gridLayout_10.addWidget(self.espessura_revest_inf_le_carg_laje, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 1, 0, 1, 1)
        self.peso_revest_inf_le_carg_laje = QtWidgets.QLineEdit(self.groupBox_2)
        self.peso_revest_inf_le_carg_laje.setObjectName("peso_revest_inf_le_carg_laje")
        self.gridLayout_10.addWidget(self.peso_revest_inf_le_carg_laje, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_11.addWidget(self.label_13, 0, 0, 1, 1)
        self.espessura_contrap_le_carg_laje = QtWidgets.QLineEdit(self.groupBox_3)
        self.espessura_contrap_le_carg_laje.setObjectName("espessura_contrap_le_carg_laje")
        self.gridLayout_11.addWidget(self.espessura_contrap_le_carg_laje, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_11.addWidget(self.label_14, 1, 0, 1, 1)
        self.peso_contrap_le_carg_laje = QtWidgets.QLineEdit(self.groupBox_3)
        self.peso_contrap_le_carg_laje.setObjectName("peso_contrap_le_carg_laje")
        self.gridLayout_11.addWidget(self.peso_contrap_le_carg_laje, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 3, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_13.addWidget(self.label_6, 0, 0, 1, 1)
        self.caso_parede_cbox_carg_laje = QtWidgets.QComboBox(self.groupBox_4)
        self.caso_parede_cbox_carg_laje.setObjectName("caso_parede_cbox_carg_laje")
        self.caso_parede_cbox_carg_laje.addItem("")
        self.caso_parede_cbox_carg_laje.addItem("")
        self.caso_parede_cbox_carg_laje.addItem("")
        self.gridLayout_13.addWidget(self.caso_parede_cbox_carg_laje, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_13.addWidget(self.label_15, 1, 0, 1, 1)
        self.espessura_parede_le_carg_laje = QtWidgets.QLineEdit(self.groupBox_4)
        self.espessura_parede_le_carg_laje.setObjectName("espessura_parede_le_carg_laje")
        self.gridLayout_13.addWidget(self.espessura_parede_le_carg_laje, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_13.addWidget(self.label_16, 2, 0, 1, 1)
        self.perimetro_parede_le_carg_laje = QtWidgets.QLineEdit(self.groupBox_4)
        self.perimetro_parede_le_carg_laje.setObjectName("perimetro_parede_le_carg_laje")
        self.gridLayout_13.addWidget(self.perimetro_parede_le_carg_laje, 2, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label_30.setObjectName("label_30")
        self.gridLayout_13.addWidget(self.label_30, 3, 0, 1, 1)
        self.altura_parede_le_carg_laje = QtWidgets.QLineEdit(self.groupBox_4)
        self.altura_parede_le_carg_laje.setObjectName("altura_parede_le_carg_laje")
        self.gridLayout_13.addWidget(self.altura_parede_le_carg_laje, 3, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 2, 0, 1, 2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setObjectName("label_17")
        self.gridLayout_12.addWidget(self.label_17, 0, 0, 1, 1)
        self.utiliz_le_carg_laje = QtWidgets.QLineEdit(self.groupBox_5)
        self.utiliz_le_carg_laje.setObjectName("utiliz_le_carg_laje")
        self.gridLayout_12.addWidget(self.utiliz_le_carg_laje, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 2, 2, 1, 1)
        self.add_btn_carg_laje = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_btn_carg_laje.sizePolicy().hasHeightForWidth())
        self.add_btn_carg_laje.setSizePolicy(sizePolicy)
        self.add_btn_carg_laje.setObjectName("add_btn_carg_laje")
        self.gridLayout_4.addWidget(self.add_btn_carg_laje, 2, 3, 1, 1)
        self.textBrowser_carg_laje = QtWidgets.QTextBrowser(self.splitter_2)
        self.textBrowser_carg_laje.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_carg_laje.setFont(font)
        self.textBrowser_carg_laje.setObjectName("textBrowser_carg_laje")
        self.gridLayout_5.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.tabWidget_laje.addTab(self.tab_5, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_11)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.splitter_3 = QtWidgets.QSplitter(self.tab_11)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.widget_3 = QtWidgets.QWidget(self.splitter_3)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_34 = QtWidgets.QLabel(self.widget_3)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 0, 0, 1, 1)
        self.nlaje_cbox_reac_laje = QtWidgets.QComboBox(self.widget_3)
        self.nlaje_cbox_reac_laje.setObjectName("nlaje_cbox_reac_laje")
        self.gridLayout_3.addWidget(self.nlaje_cbox_reac_laje, 0, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.widget_3)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_3.addWidget(self.label_35, 1, 0, 1, 1)
        self.lambda_le_reac_laje = QtWidgets.QLineEdit(self.widget_3)
        self.lambda_le_reac_laje.setEnabled(True)
        self.lambda_le_reac_laje.setText("")
        self.lambda_le_reac_laje.setReadOnly(True)
        self.lambda_le_reac_laje.setObjectName("lambda_le_reac_laje")
        self.gridLayout_3.addWidget(self.lambda_le_reac_laje, 1, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.widget_3)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_3.addWidget(self.label_36, 2, 0, 1, 1)
        self.vx_le_reac_laje = QtWidgets.QLineEdit(self.widget_3)
        self.vx_le_reac_laje.setObjectName("vx_le_reac_laje")
        self.gridLayout_3.addWidget(self.vx_le_reac_laje, 2, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.widget_3)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 3, 0, 1, 1)
        self.v_x_le_reac_laje = QtWidgets.QLineEdit(self.widget_3)
        self.v_x_le_reac_laje.setObjectName("v_x_le_reac_laje")
        self.gridLayout_3.addWidget(self.v_x_le_reac_laje, 3, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.widget_3)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 4, 0, 1, 1)
        self.vy_le_reac_laje = QtWidgets.QLineEdit(self.widget_3)
        self.vy_le_reac_laje.setObjectName("vy_le_reac_laje")
        self.gridLayout_3.addWidget(self.vy_le_reac_laje, 4, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.widget_3)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 5, 0, 1, 1)
        self.v_y_le_reac_laje = QtWidgets.QLineEdit(self.widget_3)
        self.v_y_le_reac_laje.setObjectName("v_y_le_reac_laje")
        self.gridLayout_3.addWidget(self.v_y_le_reac_laje, 5, 1, 1, 1)
        self.add_btn_reac_laje = QtWidgets.QPushButton(self.widget_3)
        self.add_btn_reac_laje.setObjectName("add_btn_reac_laje")
        self.gridLayout_3.addWidget(self.add_btn_reac_laje, 6, 0, 1, 2)
        self.textBrowser_reac_laje = QtWidgets.QTextBrowser(self.splitter_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_reac_laje.setFont(font)
        self.textBrowser_reac_laje.setObjectName("textBrowser_reac_laje")
        self.gridLayout_14.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.tabWidget_laje.addTab(self.tab_11, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.splitter_4 = QtWidgets.QSplitter(self.tab_6)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.widget_4 = QtWidgets.QWidget(self.splitter_4)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_18 = QtWidgets.QLabel(self.widget_4)
        self.label_18.setObjectName("label_18")
        self.gridLayout_15.addWidget(self.label_18, 0, 0, 1, 1)
        self.nlaje_cbox_momento_laje = QtWidgets.QComboBox(self.widget_4)
        self.nlaje_cbox_momento_laje.setObjectName("nlaje_cbox_momento_laje")
        self.gridLayout_15.addWidget(self.nlaje_cbox_momento_laje, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget_4)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_15.addWidget(self.label_19, 1, 0, 1, 1)
        self.lambda_le_momento_laje = QtWidgets.QLineEdit(self.widget_4)
        self.lambda_le_momento_laje.setEnabled(True)
        self.lambda_le_momento_laje.setReadOnly(True)
        self.lambda_le_momento_laje.setObjectName("lambda_le_momento_laje")
        self.gridLayout_15.addWidget(self.lambda_le_momento_laje, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.widget_4)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_15.addWidget(self.label_21, 2, 0, 1, 1)
        self.mx_le_momento_laje = QtWidgets.QLineEdit(self.widget_4)
        self.mx_le_momento_laje.setObjectName("mx_le_momento_laje")
        self.gridLayout_15.addWidget(self.mx_le_momento_laje, 2, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget_4)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_15.addWidget(self.label_23, 3, 0, 1, 1)
        self.nx_le_momento_laje = QtWidgets.QLineEdit(self.widget_4)
        self.nx_le_momento_laje.setObjectName("nx_le_momento_laje")
        self.gridLayout_15.addWidget(self.nx_le_momento_laje, 3, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.widget_4)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_15.addWidget(self.label_24, 4, 0, 1, 1)
        self.my_le_momento_laje = QtWidgets.QLineEdit(self.widget_4)
        self.my_le_momento_laje.setObjectName("my_le_momento_laje")
        self.gridLayout_15.addWidget(self.my_le_momento_laje, 4, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.widget_4)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_15.addWidget(self.label_25, 5, 0, 1, 1)
        self.ny_le_momento_laje = QtWidgets.QLineEdit(self.widget_4)
        self.ny_le_momento_laje.setObjectName("ny_le_momento_laje")
        self.gridLayout_15.addWidget(self.ny_le_momento_laje, 5, 1, 1, 1)
        self.add_btn_momento_laje = QtWidgets.QPushButton(self.widget_4)
        self.add_btn_momento_laje.setObjectName("add_btn_momento_laje")
        self.gridLayout_15.addWidget(self.add_btn_momento_laje, 6, 0, 1, 2)
        self.textBrowser_momentos_laje = QtWidgets.QTextBrowser(self.splitter_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_momentos_laje.setFont(font)
        self.textBrowser_momentos_laje.setObjectName("textBrowser_momentos_laje")
        self.gridLayout_16.addWidget(self.splitter_4, 0, 0, 1, 1)
        self.tabWidget_laje.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.splitter_5 = QtWidgets.QSplitter(self.tab_7)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setChildrenCollapsible(True)
        self.splitter_5.setObjectName("splitter_5")
        self.widget_5 = QtWidgets.QWidget(self.splitter_5)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.compat_table_compat_laje = QtWidgets.QTableWidget(self.widget_5)
        self.compat_table_compat_laje.setShowGrid(True)
        self.compat_table_compat_laje.setObjectName("compat_table_compat_laje")
        self.compat_table_compat_laje.setColumnCount(4)
        self.compat_table_compat_laje.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.compat_table_compat_laje.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.compat_table_compat_laje.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.compat_table_compat_laje.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.compat_table_compat_laje.setHorizontalHeaderItem(3, item)
        self.gridLayout_17.addWidget(self.compat_table_compat_laje, 0, 0, 1, 2)
        self.add_linha_btn_compat_laje = QtWidgets.QPushButton(self.widget_5)
        self.add_linha_btn_compat_laje.setObjectName("add_linha_btn_compat_laje")
        self.gridLayout_17.addWidget(self.add_linha_btn_compat_laje, 1, 0, 1, 1)
        self.remov_linha_btn_compat_laje = QtWidgets.QPushButton(self.widget_5)
        self.remov_linha_btn_compat_laje.setObjectName("remov_linha_btn_compat_laje")
        self.gridLayout_17.addWidget(self.remov_linha_btn_compat_laje, 1, 1, 1, 1)
        self.add_compt_btn_compat_laje = QtWidgets.QPushButton(self.widget_5)
        self.add_compt_btn_compat_laje.setObjectName("add_compt_btn_compat_laje")
        self.gridLayout_17.addWidget(self.add_compt_btn_compat_laje, 2, 0, 1, 2)
        self.textBrowser_compat_laje = QtWidgets.QTextBrowser(self.splitter_5)
        self.textBrowser_compat_laje.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_compat_laje.setFont(font)
        self.textBrowser_compat_laje.setObjectName("textBrowser_compat_laje")
        self.gridLayout_18.addWidget(self.splitter_5, 0, 0, 1, 1)
        self.tabWidget_laje.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.splitter_6 = QtWidgets.QSplitter(self.tab_8)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.textBrowser_dim_laje = QtWidgets.QTextBrowser(self.splitter_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_dim_laje.setFont(font)
        self.textBrowser_dim_laje.setObjectName("textBrowser_dim_laje")
        self.gridLayout_20.addWidget(self.splitter_6, 0, 0, 1, 1)
        self.tabWidget_laje.addTab(self.tab_8, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tab_16)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.splitter_14 = QtWidgets.QSplitter(self.tab_16)
        self.splitter_14.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_14.setObjectName("splitter_14")
        self.widget_14 = QtWidgets.QWidget(self.splitter_14)
        self.widget_14.setObjectName("widget_14")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.widget_14)
        self.gridLayout_34.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.nlaje_cbox_els_laje = QtWidgets.QComboBox(self.widget_14)
        self.nlaje_cbox_els_laje.setObjectName("nlaje_cbox_els_laje")
        self.gridLayout_34.addWidget(self.nlaje_cbox_els_laje, 0, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.widget_14)
        self.label_44.setObjectName("label_44")
        self.gridLayout_34.addWidget(self.label_44, 0, 0, 1, 1)
        self.verificar_btn_els_laje = QtWidgets.QPushButton(self.widget_14)
        self.verificar_btn_els_laje.setObjectName("verificar_btn_els_laje")
        self.gridLayout_34.addWidget(self.verificar_btn_els_laje, 2, 0, 1, 2)
        self.label_57 = QtWidgets.QLabel(self.widget_14)
        self.label_57.setObjectName("label_57")
        self.gridLayout_34.addWidget(self.label_57, 1, 0, 1, 1)
        self.kalmanok_le_els_laje = QtWidgets.QLineEdit(self.widget_14)
        self.kalmanok_le_els_laje.setObjectName("kalmanok_le_els_laje")
        self.gridLayout_34.addWidget(self.kalmanok_le_els_laje, 1, 1, 1, 1)
        self.textBrowser_els_laje = QtWidgets.QTextBrowser(self.splitter_14)
        self.textBrowser_els_laje.setObjectName("textBrowser_els_laje")
        self.gridLayout_19.addWidget(self.splitter_14, 0, 0, 1, 1)
        self.tabWidget_laje.addTab(self.tab_16, "")
        self.gridLayout_6.addWidget(self.tabWidget_laje, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget_Viga = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_Viga.setObjectName("tabWidget_Viga")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.splitter_7 = QtWidgets.QSplitter(self.tab_9)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.widget_7 = QtWidgets.QWidget(self.splitter_7)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_21.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_48 = QtWidgets.QLabel(self.widget_7)
        self.label_48.setObjectName("label_48")
        self.gridLayout_21.addWidget(self.label_48, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_7)
        self.label_7.setObjectName("label_7")
        self.gridLayout_21.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_7)
        self.label_10.setObjectName("label_10")
        self.gridLayout_21.addWidget(self.label_10, 1, 0, 1, 1)
        self.l_le_carac_viga = QtWidgets.QLineEdit(self.widget_7)
        self.l_le_carac_viga.setObjectName("l_le_carac_viga")
        self.gridLayout_21.addWidget(self.l_le_carac_viga, 1, 1, 1, 1)
        self.nviga_cbox_carac_viga = QtWidgets.QComboBox(self.widget_7)
        self.nviga_cbox_carac_viga.setObjectName("nviga_cbox_carac_viga")
        self.nviga_cbox_carac_viga.addItem("")
        self.gridLayout_21.addWidget(self.nviga_cbox_carac_viga, 0, 1, 1, 1)
        self.h_le_carac_viga = QtWidgets.QLineEdit(self.widget_7)
        self.h_le_carac_viga.setObjectName("h_le_carac_viga")
        self.gridLayout_21.addWidget(self.h_le_carac_viga, 2, 1, 1, 1)
        self.bw_le_carac_viga = QtWidgets.QLineEdit(self.widget_7)
        self.bw_le_carac_viga.setObjectName("bw_le_carac_viga")
        self.gridLayout_21.addWidget(self.bw_le_carac_viga, 3, 1, 1, 1)
        self.add_btn_carac_viga = QtWidgets.QPushButton(self.widget_7)
        self.add_btn_carac_viga.setObjectName("add_btn_carac_viga")
        self.gridLayout_21.addWidget(self.add_btn_carac_viga, 6, 0, 1, 2)
        self.label_20 = QtWidgets.QLabel(self.widget_7)
        self.label_20.setObjectName("label_20")
        self.gridLayout_21.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.widget_7)
        self.label_37.setObjectName("label_37")
        self.gridLayout_21.addWidget(self.label_37, 3, 0, 1, 1)
        self.remov_btn_carac_viga = QtWidgets.QPushButton(self.widget_7)
        self.remov_btn_carac_viga.setObjectName("remov_btn_carac_viga")
        self.gridLayout_21.addWidget(self.remov_btn_carac_viga, 7, 0, 1, 2)
        self.nos_le_carac_viga = QtWidgets.QLineEdit(self.widget_7)
        self.nos_le_carac_viga.setObjectName("nos_le_carac_viga")
        self.gridLayout_21.addWidget(self.nos_le_carac_viga, 4, 1, 1, 1)
        self.textBrowser_carc_viga = QtWidgets.QTextBrowser(self.splitter_7)
        self.textBrowser_carc_viga.setObjectName("textBrowser_carc_viga")
        self.gridLayout_22.addWidget(self.splitter_7, 0, 0, 1, 1)
        self.tabWidget_Viga.addTab(self.tab_9, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.tab_13)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.splitter_8 = QtWidgets.QSplitter(self.tab_13)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.widget_9 = QtWidgets.QWidget(self.splitter_8)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.widget_9)
        self.gridLayout_24.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.import_le_momentos_viga = QtWidgets.QLineEdit(self.widget_9)
        self.import_le_momentos_viga.setObjectName("import_le_momentos_viga")
        self.gridLayout_24.addWidget(self.import_le_momentos_viga, 1, 1, 1, 1)
        self.nviga_cbox_momentos_viga = QtWidgets.QComboBox(self.widget_9)
        self.nviga_cbox_momentos_viga.setObjectName("nviga_cbox_momentos_viga")
        self.gridLayout_24.addWidget(self.nviga_cbox_momentos_viga, 0, 1, 1, 1)
        self.import_btn_momentos_viga = QtWidgets.QPushButton(self.widget_9)
        self.import_btn_momentos_viga.setObjectName("import_btn_momentos_viga")
        self.gridLayout_24.addWidget(self.import_btn_momentos_viga, 1, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.widget_9)
        self.label_38.setObjectName("label_38")
        self.gridLayout_24.addWidget(self.label_38, 0, 0, 1, 1)
        self.add_btn_momentos_viga = QtWidgets.QPushButton(self.widget_9)
        self.add_btn_momentos_viga.setObjectName("add_btn_momentos_viga")
        self.gridLayout_24.addWidget(self.add_btn_momentos_viga, 3, 0, 1, 2)
        self.widget_momentos_vigas = QtWidgets.QWidget(self.splitter_8)
        self.widget_momentos_vigas.setObjectName("widget_momentos_vigas")
        self.gridLayout_25.addWidget(self.splitter_8, 0, 0, 1, 1)
        self.tabWidget_Viga.addTab(self.tab_13, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.tab_12)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.splitter_12 = QtWidgets.QSplitter(self.tab_12)
        self.splitter_12.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_12.setObjectName("splitter_12")
        self.widget_13 = QtWidgets.QWidget(self.splitter_12)
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.widget_13)
        self.gridLayout_32.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.import_btn_cortantes_viga = QtWidgets.QPushButton(self.widget_13)
        self.import_btn_cortantes_viga.setObjectName("import_btn_cortantes_viga")
        self.gridLayout_32.addWidget(self.import_btn_cortantes_viga, 1, 0, 1, 1)
        self.import_le_cortantes_viga = QtWidgets.QLineEdit(self.widget_13)
        self.import_le_cortantes_viga.setObjectName("import_le_cortantes_viga")
        self.gridLayout_32.addWidget(self.import_le_cortantes_viga, 1, 1, 1, 1)
        self.nviga_cbox_cortantes_viga = QtWidgets.QComboBox(self.widget_13)
        self.nviga_cbox_cortantes_viga.setObjectName("nviga_cbox_cortantes_viga")
        self.gridLayout_32.addWidget(self.nviga_cbox_cortantes_viga, 0, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.widget_13)
        self.label_53.setObjectName("label_53")
        self.gridLayout_32.addWidget(self.label_53, 0, 0, 1, 1)
        self.add_btn_cortantes_viga = QtWidgets.QPushButton(self.widget_13)
        self.add_btn_cortantes_viga.setObjectName("add_btn_cortantes_viga")
        self.gridLayout_32.addWidget(self.add_btn_cortantes_viga, 3, 0, 1, 2)
        self.widget_cortantes_vigas = QtWidgets.QWidget(self.splitter_12)
        self.widget_cortantes_vigas.setObjectName("widget_cortantes_vigas")
        self.gridLayout_33.addWidget(self.splitter_12, 0, 0, 1, 1)
        self.tabWidget_Viga.addTab(self.tab_12, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.tab_14)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.splitter_13 = QtWidgets.QSplitter(self.tab_14)
        self.splitter_13.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_13.setObjectName("splitter_13")
        self.widget_10 = QtWidgets.QWidget(self.splitter_13)
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.widget_10)
        self.gridLayout_26.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.nviga_cbox_dim_flex_viga = QtWidgets.QComboBox(self.widget_10)
        self.nviga_cbox_dim_flex_viga.setObjectName("nviga_cbox_dim_flex_viga")
        self.gridLayout_26.addWidget(self.nviga_cbox_dim_flex_viga, 0, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.widget_10)
        self.label_40.setObjectName("label_40")
        self.gridLayout_26.addWidget(self.label_40, 0, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.widget_10)
        self.label_41.setObjectName("label_41")
        self.gridLayout_26.addWidget(self.label_41, 1, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.widget_10)
        self.label_42.setObjectName("label_42")
        self.gridLayout_26.addWidget(self.label_42, 2, 0, 1, 1)
        self.verificar_btn_dim_flex_viga = QtWidgets.QPushButton(self.widget_10)
        self.verificar_btn_dim_flex_viga.setObjectName("verificar_btn_dim_flex_viga")
        self.gridLayout_26.addWidget(self.verificar_btn_dim_flex_viga, 3, 0, 1, 2)
        self.sec_cbox_dim_flex_viga = QtWidgets.QComboBox(self.widget_10)
        self.sec_cbox_dim_flex_viga.setObjectName("sec_cbox_dim_flex_viga")
        self.gridLayout_26.addWidget(self.sec_cbox_dim_flex_viga, 1, 1, 1, 1)
        self.comb_cbox_dim_flex_viga = QtWidgets.QComboBox(self.widget_10)
        self.comb_cbox_dim_flex_viga.setObjectName("comb_cbox_dim_flex_viga")
        self.gridLayout_26.addWidget(self.comb_cbox_dim_flex_viga, 2, 1, 1, 1)
        self.splitter_9 = QtWidgets.QSplitter(self.splitter_13)
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setObjectName("splitter_9")
        self.textBrowser_dim_flex_viga = QtWidgets.QTextBrowser(self.splitter_9)
        self.textBrowser_dim_flex_viga.setObjectName("textBrowser_dim_flex_viga")
        self.textBrowser_dim_flex_viga2 = QtWidgets.QTextBrowser(self.splitter_9)
        self.textBrowser_dim_flex_viga2.setObjectName("textBrowser_dim_flex_viga2")
        self.gridLayout_27.addWidget(self.splitter_13, 0, 0, 1, 1)
        self.tabWidget_Viga.addTab(self.tab_14, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.tab_10)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.splitter_10 = QtWidgets.QSplitter(self.tab_10)
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.textBrowser_dim_cis_viga = QtWidgets.QTextBrowser(self.splitter_10)
        self.textBrowser_dim_cis_viga.setObjectName("textBrowser_dim_cis_viga")
        self.gridLayout_29.addWidget(self.splitter_10, 0, 0, 1, 1)
        self.tabWidget_Viga.addTab(self.tab_10, "")
        self.widget1 = QtWidgets.QWidget()
        self.widget1.setObjectName("widget1")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.splitter_11 = QtWidgets.QSplitter(self.widget1)
        self.splitter_11.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_11.setObjectName("splitter_11")
        self.widget_12 = QtWidgets.QWidget(self.splitter_11)
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.widget_12)
        self.gridLayout_30.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.nviga_cbox_els_viga = QtWidgets.QComboBox(self.widget_12)
        self.nviga_cbox_els_viga.setObjectName("nviga_cbox_els_viga")
        self.gridLayout_30.addWidget(self.nviga_cbox_els_viga, 0, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.widget_12)
        self.label_43.setObjectName("label_43")
        self.gridLayout_30.addWidget(self.label_43, 0, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.widget_12)
        self.label_50.setObjectName("label_50")
        self.gridLayout_30.addWidget(self.label_50, 2, 0, 1, 1)
        self.verificar_btn_els_viga = QtWidgets.QPushButton(self.widget_12)
        self.verificar_btn_els_viga.setObjectName("verificar_btn_els_viga")
        self.gridLayout_30.addWidget(self.verificar_btn_els_viga, 5, 0, 1, 2)
        self.label_49 = QtWidgets.QLabel(self.widget_12)
        self.label_49.setObjectName("label_49")
        self.gridLayout_30.addWidget(self.label_49, 1, 0, 1, 1)
        self.sec_cbox_els_viga = QtWidgets.QComboBox(self.widget_12)
        self.sec_cbox_els_viga.setObjectName("sec_cbox_els_viga")
        self.gridLayout_30.addWidget(self.sec_cbox_els_viga, 1, 1, 1, 1)
        self.ecs_le_els_viga = QtWidgets.QLineEdit(self.widget_12)
        self.ecs_le_els_viga.setReadOnly(True)
        self.ecs_le_els_viga.setObjectName("ecs_le_els_viga")
        self.gridLayout_30.addWidget(self.ecs_le_els_viga, 2, 1, 1, 1)
        self.ieq_le_els_viga = QtWidgets.QLineEdit(self.widget_12)
        self.ieq_le_els_viga.setReadOnly(True)
        self.ieq_le_els_viga.setObjectName("ieq_le_els_viga")
        self.gridLayout_30.addWidget(self.ieq_le_els_viga, 3, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.widget_12)
        self.label_51.setObjectName("label_51")
        self.gridLayout_30.addWidget(self.label_51, 3, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.widget_12)
        self.label_52.setObjectName("label_52")
        self.gridLayout_30.addWidget(self.label_52, 4, 0, 1, 1)
        self.flecha_le_els_viga = QtWidgets.QLineEdit(self.widget_12)
        self.flecha_le_els_viga.setObjectName("flecha_le_els_viga")
        self.gridLayout_30.addWidget(self.flecha_le_els_viga, 4, 1, 1, 1)
        self.textBrowser_els_viga = QtWidgets.QTextBrowser(self.splitter_11)
        self.textBrowser_els_viga.setObjectName("textBrowser_els_viga")
        self.gridLayout_31.addWidget(self.splitter_11, 0, 0, 1, 1)
        self.tabWidget_Viga.addTab(self.widget1, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.tab_15)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.textBrowser_detalhamento_viga = QtWidgets.QTextBrowser(self.tab_15)
        self.textBrowser_detalhamento_viga.setObjectName("textBrowser_detalhamento_viga")
        self.gridLayout_28.addWidget(self.textBrowser_detalhamento_viga, 0, 0, 1, 1)
        self.tabWidget_Viga.addTab(self.tab_15, "")
        self.gridLayout_8.addWidget(self.tabWidget_Viga, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.tab_17)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.memorial_textBrowser = QtWidgets.QTextBrowser(self.tab_17)
        self.memorial_textBrowser.setObjectName("memorial_textBrowser")
        self.gridLayout_35.addWidget(self.memorial_textBrowser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_17, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 825, 21))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuAjuda = QtWidgets.QMenu(self.menubar)
        self.menuAjuda.setObjectName("menuAjuda")
        self.menuConfigura_es = QtWidgets.QMenu(self.menubar)
        self.menuConfigura_es.setObjectName("menuConfigura_es")
        self.menuCalcular = QtWidgets.QMenu(self.menubar)
        self.menuCalcular.setObjectName("menuCalcular")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNovo = QtWidgets.QAction(MainWindow)
        self.actionNovo.setObjectName("actionNovo")
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionSalvar = QtWidgets.QAction(MainWindow)
        self.actionSalvar.setObjectName("actionSalvar")
        self.actionSalvar_Como = QtWidgets.QAction(MainWindow)
        self.actionSalvar_Como.setObjectName("actionSalvar_Como")
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionSobre = QtWidgets.QAction(MainWindow)
        self.actionSobre.setObjectName("actionSobre")
        self.actionDevelopment_Tool = QtWidgets.QAction(MainWindow)
        self.actionDevelopment_Tool.setObjectName("actionDevelopment_Tool")
        self.actionCoeficientes_de_Norma = QtWidgets.QAction(MainWindow)
        self.actionCoeficientes_de_Norma.setObjectName("actionCoeficientes_de_Norma")
        self.actionPesos_Espec_ficos = QtWidgets.QAction(MainWindow)
        self.actionPesos_Espec_ficos.setObjectName("actionPesos_Espec_ficos")
        self.actionDimensionar_Lajes = QtWidgets.QAction(MainWindow)
        self.actionDimensionar_Lajes.setObjectName("actionDimensionar_Lajes")
        self.actionDimensionar_Vigas_Flexao = QtWidgets.QAction(MainWindow)
        self.actionDimensionar_Vigas_Flexao.setObjectName("actionDimensionar_Vigas_Flexao")
        self.actionDimensionar_Pilares = QtWidgets.QAction(MainWindow)
        self.actionDimensionar_Pilares.setObjectName("actionDimensionar_Pilares")
        self.actionDimensionar_Vigas_Cisalhamento = QtWidgets.QAction(MainWindow)
        self.actionDimensionar_Vigas_Cisalhamento.setObjectName("actionDimensionar_Vigas_Cisalhamento")
        self.actionEscrever_Memorial = QtWidgets.QAction(MainWindow)
        self.actionEscrever_Memorial.setObjectName("actionEscrever_Memorial")
        self.menuArquivo.addAction(self.actionNovo)
        self.menuArquivo.addAction(self.actionAbrir)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionSalvar)
        self.menuArquivo.addAction(self.actionSalvar_Como)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionSair)
        self.menuAjuda.addAction(self.actionSobre)
        self.menuAjuda.addSeparator()
        self.menuAjuda.addAction(self.actionDevelopment_Tool)
        self.menuConfigura_es.addAction(self.actionCoeficientes_de_Norma)
        self.menuConfigura_es.addAction(self.actionPesos_Espec_ficos)
        self.menuCalcular.addAction(self.actionDimensionar_Lajes)
        self.menuCalcular.addAction(self.actionDimensionar_Vigas_Flexao)
        self.menuCalcular.addAction(self.actionDimensionar_Vigas_Cisalhamento)
        self.menuCalcular.addAction(self.actionDimensionar_Pilares)
        self.menuCalcular.addAction(self.actionEscrever_Memorial)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuConfigura_es.menuAction())
        self.menubar.addAction(self.menuCalcular.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_laje.setCurrentIndex(0)
        self.tabWidget_Viga.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.nlaje_cbox_carac_laje)
        MainWindow.setTabOrder(self.nlaje_cbox_carac_laje, self.lx_le_carac_laje)
        MainWindow.setTabOrder(self.lx_le_carac_laje, self.ly_le_carac_laje)
        MainWindow.setTabOrder(self.ly_le_carac_laje, self.h_le_carac_laje)
        MainWindow.setTabOrder(self.h_le_carac_laje, self.apoio_cbox_carac_laje)
        MainWindow.setTabOrder(self.apoio_cbox_carac_laje, self.add_btn_carac_laje)
        MainWindow.setTabOrder(self.add_btn_carac_laje, self.remov_btn_carac_laje)
        MainWindow.setTabOrder(self.remov_btn_carac_laje, self.textBrowser_carc_laje)
        MainWindow.setTabOrder(self.textBrowser_carc_laje, self.nlaje_cbox_carg_laje)
        MainWindow.setTabOrder(self.nlaje_cbox_carg_laje, self.espessura_revest_sup_le_carg_laje)
        MainWindow.setTabOrder(self.espessura_revest_sup_le_carg_laje, self.peso_revest_sup_le_carg_laje)
        MainWindow.setTabOrder(self.peso_revest_sup_le_carg_laje, self.espessura_revest_inf_le_carg_laje)
        MainWindow.setTabOrder(self.espessura_revest_inf_le_carg_laje, self.peso_revest_inf_le_carg_laje)
        MainWindow.setTabOrder(self.peso_revest_inf_le_carg_laje, self.espessura_contrap_le_carg_laje)
        MainWindow.setTabOrder(self.espessura_contrap_le_carg_laje, self.peso_contrap_le_carg_laje)
        MainWindow.setTabOrder(self.peso_contrap_le_carg_laje, self.caso_parede_cbox_carg_laje)
        MainWindow.setTabOrder(self.caso_parede_cbox_carg_laje, self.espessura_parede_le_carg_laje)
        MainWindow.setTabOrder(self.espessura_parede_le_carg_laje, self.perimetro_parede_le_carg_laje)
        MainWindow.setTabOrder(self.perimetro_parede_le_carg_laje, self.altura_parede_le_carg_laje)
        MainWindow.setTabOrder(self.altura_parede_le_carg_laje, self.utiliz_le_carg_laje)
        MainWindow.setTabOrder(self.utiliz_le_carg_laje, self.add_btn_carg_laje)
        MainWindow.setTabOrder(self.add_btn_carg_laje, self.textBrowser_carg_laje)
        MainWindow.setTabOrder(self.textBrowser_carg_laje, self.nlaje_cbox_reac_laje)
        MainWindow.setTabOrder(self.nlaje_cbox_reac_laje, self.lambda_le_reac_laje)
        MainWindow.setTabOrder(self.lambda_le_reac_laje, self.vx_le_reac_laje)
        MainWindow.setTabOrder(self.vx_le_reac_laje, self.v_x_le_reac_laje)
        MainWindow.setTabOrder(self.v_x_le_reac_laje, self.vy_le_reac_laje)
        MainWindow.setTabOrder(self.vy_le_reac_laje, self.v_y_le_reac_laje)
        MainWindow.setTabOrder(self.v_y_le_reac_laje, self.add_btn_reac_laje)
        MainWindow.setTabOrder(self.add_btn_reac_laje, self.textBrowser_reac_laje)
        MainWindow.setTabOrder(self.textBrowser_reac_laje, self.nlaje_cbox_momento_laje)
        MainWindow.setTabOrder(self.nlaje_cbox_momento_laje, self.lambda_le_momento_laje)
        MainWindow.setTabOrder(self.lambda_le_momento_laje, self.mx_le_momento_laje)
        MainWindow.setTabOrder(self.mx_le_momento_laje, self.nx_le_momento_laje)
        MainWindow.setTabOrder(self.nx_le_momento_laje, self.my_le_momento_laje)
        MainWindow.setTabOrder(self.my_le_momento_laje, self.ny_le_momento_laje)
        MainWindow.setTabOrder(self.ny_le_momento_laje, self.add_btn_momento_laje)
        MainWindow.setTabOrder(self.add_btn_momento_laje, self.textBrowser_momentos_laje)
        MainWindow.setTabOrder(self.textBrowser_momentos_laje, self.compat_table_compat_laje)
        MainWindow.setTabOrder(self.compat_table_compat_laje, self.add_linha_btn_compat_laje)
        MainWindow.setTabOrder(self.add_linha_btn_compat_laje, self.remov_linha_btn_compat_laje)
        MainWindow.setTabOrder(self.remov_linha_btn_compat_laje, self.add_compt_btn_compat_laje)
        MainWindow.setTabOrder(self.add_compt_btn_compat_laje, self.textBrowser_compat_laje)
        MainWindow.setTabOrder(self.textBrowser_compat_laje, self.textBrowser_dim_laje)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ConcretePy"))
        self.label_2.setText(_translate("MainWindow", "Comprimento da direção principal (cm)"))
        self.label_22.setText(_translate("MainWindow", "Tipo de Apoio"))
        self.nlaje_cbox_carac_laje.setItemText(0, _translate("MainWindow", "1"))
        self.remov_btn_carac_laje.setText(_translate("MainWindow", "Remover Laje"))
        self.apoio_cbox_carac_laje.setItemText(0, _translate("MainWindow", "Caso 1 - Ax1-Ax2-Ay1-Ay2"))
        self.apoio_cbox_carac_laje.setItemText(1, _translate("MainWindow", "Caso 2A - Ex1-Ax2-Ay1-Ay2"))
        self.apoio_cbox_carac_laje.setItemText(2, _translate("MainWindow", "Caso 2B - Ax1-Ax2-Ey1-Ay2"))
        self.apoio_cbox_carac_laje.setItemText(3, _translate("MainWindow", "Caso 3 - Ex1-Ax2-Ey1-Ay2"))
        self.apoio_cbox_carac_laje.setItemText(4, _translate("MainWindow", "Caso 4A - Ex1-Ex2-Ay1-Ay2"))
        self.apoio_cbox_carac_laje.setItemText(5, _translate("MainWindow", "Caso 4B - Ax1-Ax2-Ey1-Ey2"))
        self.apoio_cbox_carac_laje.setItemText(6, _translate("MainWindow", "Caso 5A - Ex1-Ex2-Ey1-Ay2"))
        self.apoio_cbox_carac_laje.setItemText(7, _translate("MainWindow", "Caso 5B - Ex1-Ax2-Ey1-Ey2"))
        self.apoio_cbox_carac_laje.setItemText(8, _translate("MainWindow", "Caso 6 - Ex1-Ex2-Ey1-Ey2"))
        self.lx_le_carac_laje.setPlaceholderText(_translate("MainWindow", "lx"))
        self.label_4.setText(_translate("MainWindow", "Espessura de pré-dimensionamento (cm)"))
        self.h_le_carac_laje.setPlaceholderText(_translate("MainWindow", "h"))
        self.label_3.setText(_translate("MainWindow", "Comprimento da direção secundária (cm)"))
        self.add_btn_carac_laje.setText(_translate("MainWindow", "Adicionar Laje"))
        self.ly_le_carac_laje.setPlaceholderText(_translate("MainWindow", "ly"))
        self.label.setText(_translate("MainWindow", "Número da laje"))
        self.textBrowser_carc_laje.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.tabWidget_laje.setTabText(self.tabWidget_laje.indexOf(self.tab_4), _translate("MainWindow", "Caracterização"))
        self.label_5.setText(_translate("MainWindow", "Número da Laje"))
        self.groupBox.setTitle(_translate("MainWindow", "Revestimento Superior"))
        self.label_8.setText(_translate("MainWindow", "Espessura (cm)"))
        self.label_9.setText(_translate("MainWindow", "Peso Específico (kN/m³)"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Revestimento Inferior"))
        self.label_11.setText(_translate("MainWindow", "Espessura (cm)"))
        self.label_12.setText(_translate("MainWindow", "Peso Específico (kN/m³)"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Contrapiso"))
        self.label_13.setText(_translate("MainWindow", "Espessura (cm)"))
        self.label_14.setText(_translate("MainWindow", "Peso Específico (kN/m³)"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Parede"))
        self.label_6.setText(_translate("MainWindow", "Caso"))
        self.caso_parede_cbox_carg_laje.setItemText(0, _translate("MainWindow", "Laje em cruz"))
        self.caso_parede_cbox_carg_laje.setItemText(1, _translate("MainWindow", "Paralelo ao menor vao"))
        self.caso_parede_cbox_carg_laje.setItemText(2, _translate("MainWindow", "Perpendicular ao menor vao"))
        self.label_15.setText(_translate("MainWindow", "Espessura (cm)"))
        self.label_16.setText(_translate("MainWindow", "Perímetro (cm)"))
        self.label_30.setText(_translate("MainWindow", "Altura (cm)"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Acidental, Utilização e Serviço"))
        self.label_17.setText(_translate("MainWindow", "Carga (kN/m²)"))
        self.add_btn_carg_laje.setText(_translate("MainWindow", "Adicionar Para Essa Laje"))
        self.tabWidget_laje.setTabText(self.tabWidget_laje.indexOf(self.tab_5), _translate("MainWindow", "Cargas"))
        self.label_34.setText(_translate("MainWindow", "Número da Laje"))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">λ</span></p></body></html>"))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">ν</span><span style=\" font-size:11pt; vertical-align:sub;\">x</span></p></body></html>"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">ν\'</span><span style=\" font-size:11pt; vertical-align:sub;\">x</span></p></body></html>"))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">ν</span><span style=\" font-size:12pt; vertical-align:sub;\">y</span></p></body></html>"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">ν\'</span><span style=\" font-size:12pt; vertical-align:sub;\">y</span></p></body></html>"))
        self.add_btn_reac_laje.setText(_translate("MainWindow", "Confirmar Reações"))
        self.tabWidget_laje.setTabText(self.tabWidget_laje.indexOf(self.tab_11), _translate("MainWindow", "Reações"))
        self.label_18.setText(_translate("MainWindow", "Número da Laje"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">λ</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">μ</span><span style=\" font-size:12pt; vertical-align:sub;\">x</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">μ\'</span><span style=\" font-size:12pt; vertical-align:sub;\">x</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">μ</span><span style=\" font-size:12pt; vertical-align:sub;\">y</span></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">μ\'</span><span style=\" font-size:12pt; vertical-align:sub;\">y</span></p></body></html>"))
        self.add_btn_momento_laje.setText(_translate("MainWindow", "Confirmar Momentos"))
        self.tabWidget_laje.setTabText(self.tabWidget_laje.indexOf(self.tab_6), _translate("MainWindow", "Momentos"))
        self.compat_table_compat_laje.setSortingEnabled(False)
        item = self.compat_table_compat_laje.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Laje A"))
        item = self.compat_table_compat_laje.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Bordo A"))
        item = self.compat_table_compat_laje.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Laje B"))
        item = self.compat_table_compat_laje.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Bordo B"))
        self.add_linha_btn_compat_laje.setText(_translate("MainWindow", "Adicionar Linha"))
        self.remov_linha_btn_compat_laje.setText(_translate("MainWindow", "Remover Linha"))
        self.add_compt_btn_compat_laje.setText(_translate("MainWindow", "Compatibilizar Momentos"))
        self.tabWidget_laje.setTabText(self.tabWidget_laje.indexOf(self.tab_7), _translate("MainWindow", "Compatibilização"))
        self.tabWidget_laje.setTabText(self.tabWidget_laje.indexOf(self.tab_8), _translate("MainWindow", "Detalhamento"))
        self.label_44.setText(_translate("MainWindow", "Número da Laje"))
        self.verificar_btn_els_laje.setText(_translate("MainWindow", "Verificar ELS"))
        self.label_57.setText(_translate("MainWindow", "Coeficiente de Kalmanok"))
        self.tabWidget_laje.setTabText(self.tabWidget_laje.indexOf(self.tab_16), _translate("MainWindow", "Verificação ELS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Lajes"))
        self.label_48.setText(_translate("MainWindow", "Nós (tuple - m)"))
        self.label_7.setText(_translate("MainWindow", "Número da Viga"))
        self.label_10.setText(_translate("MainWindow", "Comprimento da Viga (m)"))
        self.nviga_cbox_carac_viga.setItemText(0, _translate("MainWindow", "1"))
        self.add_btn_carac_viga.setText(_translate("MainWindow", "Adicionar Viga"))
        self.label_20.setText(_translate("MainWindow", "Altura da Viga (cm)"))
        self.label_37.setText(_translate("MainWindow", "Largura da Viga (cm)"))
        self.remov_btn_carac_viga.setText(_translate("MainWindow", "Remover Viga"))
        self.tabWidget_Viga.setTabText(self.tabWidget_Viga.indexOf(self.tab_9), _translate("MainWindow", "Caracterização"))
        self.import_btn_momentos_viga.setText(_translate("MainWindow", "Arquivo FTOOL"))
        self.label_38.setText(_translate("MainWindow", "Número da Viga"))
        self.add_btn_momentos_viga.setText(_translate("MainWindow", "Adicionar Momentos"))
        self.tabWidget_Viga.setTabText(self.tabWidget_Viga.indexOf(self.tab_13), _translate("MainWindow", "Diagramas de Momento"))
        self.import_btn_cortantes_viga.setText(_translate("MainWindow", "Arquivo FTOOL"))
        self.label_53.setText(_translate("MainWindow", "Número da Viga"))
        self.add_btn_cortantes_viga.setText(_translate("MainWindow", "Adicionar Cortantes"))
        self.tabWidget_Viga.setTabText(self.tabWidget_Viga.indexOf(self.tab_12), _translate("MainWindow", "Diagrama de Cortante"))
        self.label_40.setText(_translate("MainWindow", "Número da Viga"))
        self.label_41.setText(_translate("MainWindow", "Seção da Viga"))
        self.label_42.setText(_translate("MainWindow", "Combinação Escolhida"))
        self.verificar_btn_dim_flex_viga.setText(_translate("MainWindow", "Confirmar Escolha"))
        self.tabWidget_Viga.setTabText(self.tabWidget_Viga.indexOf(self.tab_14), _translate("MainWindow", "Dimensionamento à Flexão"))
        self.tabWidget_Viga.setTabText(self.tabWidget_Viga.indexOf(self.tab_10), _translate("MainWindow", "Dimensionamento ao Cisalhamento"))
        self.label_43.setText(_translate("MainWindow", "Número da Viga"))
        self.label_50.setText(_translate("MainWindow", "Ecs"))
        self.verificar_btn_els_viga.setText(_translate("MainWindow", "Verificar ELS"))
        self.label_49.setText(_translate("MainWindow", "Seção da Viga"))
        self.label_51.setText(_translate("MainWindow", "Ieq"))
        self.label_52.setText(_translate("MainWindow", "Flecha Máxima"))
        self.tabWidget_Viga.setTabText(self.tabWidget_Viga.indexOf(self.widget1), _translate("MainWindow", "Verificação ELS"))
        self.tabWidget_Viga.setTabText(self.tabWidget_Viga.indexOf(self.tab_15), _translate("MainWindow", "Detalhamento"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Vigas"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Pilares"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_17), _translate("MainWindow", "Memorial de Cálculo"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuAjuda.setTitle(_translate("MainWindow", "Ajuda"))
        self.menuConfigura_es.setTitle(_translate("MainWindow", "Configurações"))
        self.menuCalcular.setTitle(_translate("MainWindow", "Calcular"))
        self.actionNovo.setText(_translate("MainWindow", "Novo..."))
        self.actionNovo.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir..."))
        self.actionAbrir.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSalvar.setText(_translate("MainWindow", "Salvar"))
        self.actionSalvar.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSalvar_Como.setText(_translate("MainWindow", "Salvar Como..."))
        self.actionSalvar_Como.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
        self.actionSair.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSobre.setText(_translate("MainWindow", "Sobre"))
        self.actionSobre.setShortcut(_translate("MainWindow", "F1"))
        self.actionDevelopment_Tool.setText(_translate("MainWindow", "Development Tool"))
        self.actionDevelopment_Tool.setShortcut(_translate("MainWindow", "F10"))
        self.actionCoeficientes_de_Norma.setText(_translate("MainWindow", "Coeficientes de Norma..."))
        self.actionPesos_Espec_ficos.setText(_translate("MainWindow", "Pesos Específicos..."))
        self.actionDimensionar_Lajes.setText(_translate("MainWindow", "Dimensionar Lajes"))
        self.actionDimensionar_Lajes.setShortcut(_translate("MainWindow", "Ctrl+Shift+F1"))
        self.actionDimensionar_Vigas_Flexao.setText(_translate("MainWindow", "Dimensionar Vigas - Flexão"))
        self.actionDimensionar_Vigas_Flexao.setShortcut(_translate("MainWindow", "Ctrl+Shift+F2"))
        self.actionDimensionar_Pilares.setText(_translate("MainWindow", "Dimensionar Pilares"))
        self.actionDimensionar_Pilares.setShortcut(_translate("MainWindow", "Ctrl+Shift+F4"))
        self.actionDimensionar_Vigas_Cisalhamento.setText(_translate("MainWindow", "Dimensionar Vigas - Cisalhamento"))
        self.actionDimensionar_Vigas_Cisalhamento.setShortcut(_translate("MainWindow", "Ctrl+Shift+F3"))
        self.actionEscrever_Memorial.setText(_translate("MainWindow", "Escrever Memorial"))
        self.actionEscrever_Memorial.setShortcut(_translate("MainWindow", "Ctrl+Shift+F10"))

